name: Sync Fork

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync upstream changes
        uses: dabreadman/fork-sync-with-upstream-action@v1
        with:
          upstream_repository: djteang/OrangeTV
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
